### PR TITLE
SQLReader and SQLReadWriter

### PR DESCRIPTION
**Pull request by teresa-recursion**
Move some of the utils used in platelet here so that they can be used in platelet and cdd-export (rather than duplicated in both).

### CODE REVIEW

**Review by anthuswilliams — APPROVED** [review]

**Comment by bsukow** [comment]
I'm not convinced this is necessarily better than duplication - the ported code doesn't seem to have have tests or documentation. For the tests that we do have in this repo, we don't appear to be running them in the CI environment. If these break within platelet, then at least we have tests that catch the failure.

**Comment by teresa-recursion** [comment]
@bsukow The tests for this repo do run here, maybe I'm misunderstanding what you mean?

https://travis-ci.org/recursionpharma/go-dbutil/builds/510100992?utm_source=github_status&utm_medium=notification

**Comment by bsukow** [comment]
Ah, they do. I missed that when I looked at the .travs.yml file.

**Comment by teresa-recursion** [comment]
@bsukow you do still have a point about not adding tests for  this PR though...  The 2 functions that I moved over `MustConnect` and `BeginX` didn't have tests in platelet and I didn't add any here.  I can look into writing tests for them.  :+1:

**Pull request merged**
